[tasks.build_openwrt]
env = { CONFIG_PATH = "/etc/forward_bot.toml" }
command = "rustup"
args = ["run", "nightly", "--", "cargo", "build", "-Z", "build-std=std,panic_abort", "--target", "mipsel-unknown-linux-musl", "--release"]
